version: '3'
services:
  fury-1:
    image: "fury/fury:${FURY_IMAGE_TAG:-master}"
    ports:
      # open default fury rpc port
      - "26657:26657"
      # open rest port
      - "1317:1317"
      # open grpc port
      - "9090:9090"
      # open grpc-web port
      - "9091:9091"
      # open EVM JSON-RPC port
      - "8545:8545"
      # open Eth websocket port
      - "8546:8546"
    volumes:
      - "./fury-1:/root/.fury"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.fury/config/init-data-directory.sh && fury start --rpc.laddr=tcp://0.0.0.0:26657 --x-crisis-skip-assert-invariants"
  fury-2:
    image: "fury/fury:${FURY_IMAGE_TAG:-master}"
    volumes:
      - "./fury-2:/root/.fury"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.fury/config/init-data-directory.sh && fury start --rpc.laddr=tcp://0.0.0.0:26657 --x-crisis-skip-assert-invariants"
  fury-3:
    image: "fury/fury:${FURY_IMAGE_TAG:-master}"
    volumes:
      - "./fury-3:/root/.fury"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.fury/config/init-data-directory.sh && fury start --rpc.laddr=tcp://0.0.0.0:26657 --x-crisis-skip-assert-invariants"
  fury-4:
    image: "fury/fury:${FURY_IMAGE_TAG:-master}"
    volumes:
      - "./fury-4:/root/.fury"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.fury/config/init-data-directory.sh && fury start --rpc.laddr=tcp://0.0.0.0:26657 --x-crisis-skip-assert-invariants"
  fury-5:
    image: "fury/fury:${FURY_IMAGE_TAG:-master}"
    volumes:
      - "./fury-5:/root/.fury"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.fury/config/init-data-directory.sh && fury start --rpc.laddr=tcp://0.0.0.0:26657 --x-crisis-skip-assert-invariants"
  fury-6:
    image: "fury/fury:${FURY_IMAGE_TAG:-master}"
    volumes:
      - "./fury-6:/root/.fury"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.fury/config/init-data-directory.sh && fury start --rpc.laddr=tcp://0.0.0.0:26657 --x-crisis-skip-assert-invariants"
  fury-7:
    image: "fury/fury:${FURY_IMAGE_TAG:-master}"
    volumes:
      - "./fury-7:/root/.fury"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.fury/config/init-data-directory.sh && fury start --rpc.laddr=tcp://0.0.0.0:26657 --x-crisis-skip-assert-invariants"
  fury-8:
    image: "fury/fury:${FURY_IMAGE_TAG:-master}"
    volumes:
      - "./fury-8:/root/.fury"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.fury/config/init-data-directory.sh && fury start --rpc.laddr=tcp://0.0.0.0:26657 --x-crisis-skip-assert-invariants"
  fury-9:
    image: "fury/fury:${FURY_IMAGE_TAG:-master}"
    volumes:
      - "./fury-9:/root/.fury"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.fury/config/init-data-directory.sh && fury start --rpc.laddr=tcp://0.0.0.0:26657 --x-crisis-skip-assert-invariants"
  fury-10:
    image: "fury/fury:${FURY_IMAGE_TAG:-master}"
    volumes:
      - "./fury-10:/root/.fury"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.fury/config/init-data-directory.sh && fury start --rpc.laddr=tcp://0.0.0.0:26657 --x-crisis-skip-assert-invariants"
  fury-11:
    image: "fury/fury:${FURY_IMAGE_TAG:-master}"
    volumes:
      - "./fury-11:/root/.fury"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.fury/config/init-data-directory.sh && fury start --rpc.laddr=tcp://0.0.0.0:26657 --x-crisis-skip-assert-invariants"
  fury-12:
    image: "fury/fury:${FURY_IMAGE_TAG:-master}"
    volumes:
      - "./fury-12:/root/.fury"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.fury/config/init-data-directory.sh && fury start --rpc.laddr=tcp://0.0.0.0:26657 --x-crisis-skip-assert-invariants"
  fury-13:
    image: "fury/fury:${FURY_IMAGE_TAG:-master}"
    volumes:
      - "./fury-13:/root/.fury"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.fury/config/init-data-directory.sh && fury start --rpc.laddr=tcp://0.0.0.0:26657 --x-crisis-skip-assert-invariants"
