version: '3'
services:
    furynode:
        image: "fury/fury:${FURY_TAG:-v0.16}"
        ports:
            # open default fury rpc port
            - "26657:26657"
            # open rest port
            - "1317:1317"
            # open grpc port
            - "9090:9090"
            # open grpc-web port
            - "9091:9091"
        volumes:
            - "./fury/initstate/.fury/config:/root/.fury/config"
            - "./fury/initstate/.fury/keyring-test/:/root/.fury/keyring-test"
        # start the blockchain, and set rpc to listen to connections from outside the container
        command: ["sh", "-c", "/root/.fury/config/init-data-directory.sh && fury start --rpc.laddr=tcp://0.0.0.0:26657"]
