version: '3'
services:
    furynode:
        image: "fury/fury:${FURY_TAG:-v0.21.0}"
        ports:
            # open default fury rpc port
            - "26657:26657"
            # open rest port
            - "1317:1317"
            # open grpc port
            - "9090:9090"
            # open grpc-web port
            - "9091:9091"
            # open EVM JSON-RPC port
            - "8545:8545"
            # open Eth websocket port
            - "8546:8546"
        volumes:
            - "./fury/initstate/.fury:/root/.fury"
        # start the blockchain, and set rpc to listen to connections from outside the container
        command:
            - "sh"
            - "-c"
            - "/root/.fury/config/init-data-directory.sh && fury start --rpc.laddr=tcp://0.0.0.0:26657"
